name: Conditional Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_ENV: "production"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run only in production
        if: env.MY_ENV == 'production'
        run: echo "This runs in production!"
      - name: Run always
        run: echo "This runs every time!"
